--
-- PostgreSQL database dump
--

\restrict dZUVOeF3aXlo9yT5n30vqAU6dNkoAtLx1kkd9pXqsbfajmAkSG0bc6S3sfpznGg

-- Dumped from database version 18.3 (Debian 18.3-1.pgdg12+1)
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: masco_db_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO masco_db_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO masco_db_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO masco_db_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO masco_db_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO masco_db_user;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO masco_db_user;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO masco_db_user;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO masco_db_user;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO masco_db_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO masco_db_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO masco_db_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_rest_passwordreset_resetpasswordtoken; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.django_rest_passwordreset_resetpasswordtoken (
    created_at timestamp with time zone CONSTRAINT django_rest_passwordreset_resetpasswordtoke_created_at_not_null NOT NULL,
    key character varying(64) NOT NULL,
    ip_address inet,
    user_agent character varying(512) CONSTRAINT django_rest_passwordreset_resetpasswordtoke_user_agent_not_null NOT NULL,
    user_id integer NOT NULL,
    id integer NOT NULL
);


ALTER TABLE public.django_rest_passwordreset_resetpasswordtoken OWNER TO masco_db_user;

--
-- Name: django_rest_passwordreset_resetpasswordtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.django_rest_passwordreset_resetpasswordtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_rest_passwordreset_resetpasswordtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO masco_db_user;

--
-- Name: payments_payment; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.payments_payment (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    reference character varying(200) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.payments_payment OWNER TO masco_db_user;

--
-- Name: payments_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.payments_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_cart; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.shop_cart (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT shop_cart_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.shop_cart OWNER TO masco_db_user;

--
-- Name: shop_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.shop_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_category; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.shop_category (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(50) NOT NULL
);


ALTER TABLE public.shop_category OWNER TO masco_db_user;

--
-- Name: shop_category_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.shop_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_enquiry; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.shop_enquiry (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    email character varying(254) NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.shop_enquiry OWNER TO masco_db_user;

--
-- Name: shop_enquiry_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.shop_enquiry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_enquiry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_order; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.shop_order (
    id bigint NOT NULL,
    full_name character varying(255) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(20) NOT NULL,
    billing_address text NOT NULL,
    shipping_address text NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    status character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.shop_order OWNER TO masco_db_user;

--
-- Name: shop_order_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.shop_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_product; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.shop_product (
    id bigint NOT NULL,
    "SIZES" character varying(5) NOT NULL,
    "COLOR" character varying(10) NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(50) NOT NULL,
    price numeric(10,2) NOT NULL,
    description text NOT NULL,
    stock integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT shop_product_stock_check CHECK ((stock >= 0))
);


ALTER TABLE public.shop_product OWNER TO masco_db_user;

--
-- Name: shop_product_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.shop_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_productimage; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.shop_productimage (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    image_url character varying(200)
);


ALTER TABLE public.shop_productimage OWNER TO masco_db_user;

--
-- Name: shop_productimage_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.shop_productimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_productimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shop_review; Type: TABLE; Schema: public; Owner: masco_db_user
--

CREATE TABLE public.shop_review (
    id bigint NOT NULL,
    rating smallint NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT shop_review_rating_check CHECK ((rating >= 0))
);


ALTER TABLE public.shop_review OWNER TO masco_db_user;

--
-- Name: shop_review_id_seq; Type: SEQUENCE; Schema: public; Owner: masco_db_user
--

ALTER TABLE public.shop_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shop_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Token	7	add_token
26	Can change Token	7	change_token
27	Can delete Token	7	delete_token
28	Can view Token	7	view_token
29	Can add Token	8	add_tokenproxy
30	Can change Token	8	change_tokenproxy
31	Can delete Token	8	delete_tokenproxy
32	Can view Token	8	view_tokenproxy
33	Can add Password Reset Token	9	add_resetpasswordtoken
34	Can change Password Reset Token	9	change_resetpasswordtoken
35	Can delete Password Reset Token	9	delete_resetpasswordtoken
36	Can view Password Reset Token	9	view_resetpasswordtoken
37	Can add payment	10	add_payment
38	Can change payment	10	change_payment
39	Can delete payment	10	delete_payment
40	Can view payment	10	view_payment
41	Can add address	11	add_address
42	Can change address	11	change_address
43	Can delete address	11	delete_address
44	Can view address	11	view_address
45	Can add category	13	add_category
46	Can change category	13	change_category
47	Can delete category	13	delete_category
48	Can view category	13	view_category
49	Can add enquiry	14	add_enquiry
50	Can change enquiry	14	change_enquiry
51	Can delete enquiry	14	delete_enquiry
52	Can view enquiry	14	view_enquiry
53	Can add product	16	add_product
54	Can change product	16	change_product
55	Can delete product	16	delete_product
56	Can view product	16	view_product
57	Can add cart	12	add_cart
58	Can change cart	12	change_cart
59	Can delete cart	12	delete_cart
60	Can view cart	12	view_cart
61	Can add product image	17	add_productimage
62	Can change product image	17	change_productimage
63	Can delete product image	17	delete_productimage
64	Can view product image	17	view_productimage
65	Can add review	18	add_review
66	Can change review	18	change_review
67	Can delete review	18	delete_review
68	Can view review	18	view_review
69	Can add order	15	add_order
70	Can change order	15	change_order
71	Can delete order	15	delete_order
72	Can view order	15	view_order
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$1200000$pWjHdE7nxeEsrk0Ichb9AI$D9x3dbMeK981+c3kCsNbM4WZl11/gEj/Sd+0Snzrhus=	\N	f	frankgideongeefrank@yahoo.com	Frank	Geek	frankgideongeefrank@yahoo.com	f	t	2026-04-12 21:45:17.585505+00
4	pbkdf2_sha256$1200000$0H01KzaZRrJ7xGl2dW7P1S$Ihc1rAvp50780QkEBhtbsBtbBWXj3/BCqpNmd24eoYE=	\N	f	gidfrank00@gmail.com	Gid	Frank	gidfrank00@gmail.com	f	t	2026-04-16 06:32:46.439711+00
6	pbkdf2_sha256$1200000$8Tsr5ieDQYEruMlMrOKkru$HC+hZWKHqPfCJEZs74WItqjqxKs7G+iE2jkcOQzQuNE=	\N	f	gekibade@gmail.com	Gideon	Eki	gekibade@gmail.com	f	t	2026-04-16 08:06:12.058139+00
3	pbkdf2_sha256$1200000$rSkfbEwS4Gcd5RUjYe7z2D$S+LdUMtsQJVNtjMNUoMNek/4Ky45M8fgy9IadsK4Tuc=	\N	f	g.mark700@yahoo.com	Mark	Gee	g.mark700@yahoo.com	f	t	2026-04-13 17:17:23.981221+00
7	pbkdf2_sha256$1200000$0gbk6f7xwQ7OYQ3Yv7jxbj$2FDYppIIq14nCnk3QmTPOQ6K0He6PZoRHqUdjnmhuOE=	\N	f	frankgideongefrank@yahoo.com	Frank	Gideon	frankgideongefrank@yahoo.com	f	t	2026-04-19 14:26:13.690309+00
8	pbkdf2_sha256$1200000$DusnoP15tu4hp4PoyikklA$ckzgRqIk9aXlfE1xGVO3cy8XludV5ZTtBBPykkt19uE=	\N	f	gefrank59@gmail.com	Frank	Gee	gefrank59@gmail.com	f	t	2026-04-19 20:42:06.699153+00
9	pbkdf2_sha256$1200000$sOjvecpAyyZmhvEBt158hD$9wGkcSdYDsvIy/uDbh+GdV7za2Ait21tJRI0WbFSOKs=	\N	f	gideonekibade651@gmail.com	kiba	Gid	gideonekibade651@gmail.com	f	f	2026-04-19 21:15:05.233642+00
10	pbkdf2_sha256$1200000$eew2fzXPsRG4EbHTJWRQiT$0ABDnom9K18PgZfEm3smmqlcd/vh5YWDux5kg8568OI=	\N	f	gidfrank63@yahoo.com	Gideon	frank	gidfrank63@yahoo.com	f	f	2026-04-19 21:33:43.005587+00
11	pbkdf2_sha256$1200000$od5V0vZ4dpO7WhYPdoMc11$UD+uLyDXJNjdjcatCntFb+q604qjNwdONvw7v0QkJhU=	\N	f	ekibadegideon991@gmail.com	Gid	frank	ekibadegideon991@gmail.com	f	f	2026-04-19 21:41:13.550283+00
5	pbkdf2_sha256$1200000$tqtIXFjuXzT5tu3XOZpbhE$EuR0JHU06fycS/TMVERpvrr1YKThOMjGpgktLRArsx8=	\N	f	uzoglory840@gmail.com	Glory	Uzoma	uzoglory840@gmail.com	f	t	2026-04-16 07:55:46.28419+00
12	pbkdf2_sha256$1200000$7fyOvVXTTKFe5zQtxGsChQ$Y93jMiyutfl1J3ET/LZ1XdISSL1I64Z4Tti79E5a+Tc=	\N	f	ekibadeglory@gmail.com	Glo	Eki	ekibadeglory@gmail.com	f	t	2026-04-20 20:47:59.547876+00
13	pbkdf2_sha256$1200000$TJyYR8kBTt1tIre0Z3CTWl$Y2mt2TqwuaWbM5O9/6eMa7+9dRiyMfIeIPjLu+sdJXI=	\N	f	glory.ekibade@toriloacademy.com	Glory	EEE	glory.ekibade@toriloacademy.com	f	t	2026-04-21 21:11:06.223813+00
1	pbkdf2_sha256$1200000$3DA1VpotSeAMNxWoCKoSyB$uGXW/jZLuIyuyAz/TGGaaXFDU5w6VOk6f+cE5iTAC4U=	2026-04-29 20:52:12.13766+00	t	Gideon			ekibade.gideon@yahoo.com	t	t	2026-04-12 21:39:39.324187+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
9be8ede95be1cdfe60499332df744e25ffa3c902	2026-04-12 21:45:20.988454+00	2
5f8c8ed46cb2916db1190b35f19c95ccfc423324	2026-04-13 17:17:26.576323+00	3
4c25a4e2e85c82e27e24f2907bcaf89c58c71e04	2026-04-16 06:32:49.364175+00	4
29c5d15e08aabc80c6ff5ad0882c0103b9fe3a7b	2026-04-16 07:55:48.685287+00	5
af1fdef464821808094131af78d04ea8cc5f0a19	2026-04-16 08:06:14.279111+00	6
350df581f833ed28ab6b07e9c23af99182bb1518	2026-04-19 14:26:15.993811+00	7
5a4e81c152b9ed54b12a594dac42ae5d7ca9c56e	2026-04-19 20:42:09.517768+00	8
184c0e1d41066215467776fe81b23fb113414ed2	2026-04-19 21:15:08.094489+00	9
e82420bc4baea70628b7a35a4676c63b8e94eaaf	2026-04-19 21:33:45.492081+00	10
0cff42e3e1a0a4147550de3e2f77ceaae0a695c0	2026-04-19 21:41:16.089442+00	11
c950f30a96e1d367f5644973896cb7fb43eed386	2026-04-20 20:48:02.675911+00	12
9a165f6c4c1d34300cfbba2e20eaa88148f99dfe	2026-04-21 21:11:08.780995+00	13
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-04-13 17:13:21.488721+00	1	Summer design	1	[{"added": {}}]	13	1
2	2026-04-13 17:13:52.66597+00	1	Summer design	1	[{"added": {}}]	16	1
3	2026-04-13 17:14:34.576541+00	1	Image for Summer design	1	[{"added": {}}]	17	1
4	2026-04-13 17:14:53.0704+00	2	Image for Summer design	1	[{"added": {}}]	17	1
5	2026-04-18 22:38:16.85941+00	3	g.mark700@yahoo.com	2	[{"changed": {"fields": ["password"]}}]	4	1
6	2026-04-20 21:33:14.861102+00	2	A new summer wear	1	[{"added": {}}]	13	1
7	2026-04-20 21:33:55.321361+00	2	A new summer wear	1	[{"added": {}}]	16	1
8	2026-04-20 21:34:40.184102+00	3	Image for A new summer wear	1	[{"added": {}}]	17	1
9	2026-04-20 21:35:05.921231+00	4	Image for A new summer wear	1	[{"added": {}}]	17	1
10	2026-04-25 22:10:27.101624+00	5	Image for Summer design	1	[{"added": {}}]	17	1
11	2026-04-25 22:10:44.990408+00	6	Image for Summer design	1	[{"added": {}}]	17	1
12	2026-04-25 22:14:36.580482+00	7	Image for Summer design	1	[{"added": {}}]	17	1
13	2026-04-25 22:14:56.314163+00	8	Image for Summer design	1	[{"added": {}}]	17	1
14	2026-04-25 22:15:23.794831+00	6	Image for Summer design	3		17	1
15	2026-04-25 22:15:23.794878+00	5	Image for Summer design	3		17	1
16	2026-04-26 06:02:05.275083+00	8	Image for Summer design	2	[]	17	1
17	2026-04-26 06:35:24.535601+00	3	Spring female jacket	1	[{"added": {}}]	13	1
18	2026-04-26 06:36:42.061193+00	3	Spring female jacket	1	[{"added": {}}]	16	1
19	2026-04-26 06:37:29.441658+00	9	Image for Spring female jacket	1	[{"added": {}}]	17	1
20	2026-04-26 06:38:18.037168+00	10	Image for Spring female jacket	1	[{"added": {}}]	17	1
21	2026-04-26 06:38:48.783423+00	11	Image for Spring female jacket	1	[{"added": {}}]	17	1
22	2026-04-26 06:53:32.742803+00	12	Image for A new summer wear	1	[{"added": {}}]	17	1
23	2026-04-26 07:02:25.239529+00	4	male jean, top and show	1	[{"added": {}}]	13	1
24	2026-04-26 07:02:48.67151+00	4	Male jean, top and show	1	[{"added": {}}]	16	1
25	2026-04-26 07:03:11.937196+00	13	Image for Male jean, top and show	1	[{"added": {}}]	17	1
26	2026-04-26 07:03:25.496629+00	14	Image for Male jean, top and show	1	[{"added": {}}]	17	1
27	2026-04-26 07:05:08.060644+00	5	Male summer jacket	1	[{"added": {}}]	13	1
28	2026-04-26 07:05:28.518357+00	5	Male summer jacket	1	[{"added": {}}]	16	1
29	2026-04-26 07:05:44.980541+00	15	Image for Male summer jacket	1	[{"added": {}}]	17	1
30	2026-04-26 07:09:18.8714+00	6	Female bum short	1	[{"added": {}}]	13	1
31	2026-04-26 07:09:40.212663+00	6	Female bum short	1	[{"added": {}}]	16	1
32	2026-04-26 07:09:55.48987+00	16	Image for Female bum short	1	[{"added": {}}]	17	1
33	2026-04-26 07:11:32.272438+00	7	Female nice bum short	1	[{"added": {}}]	13	1
34	2026-04-26 07:11:55.332091+00	7	Female nice bum short	1	[{"added": {}}]	16	1
35	2026-04-26 07:12:18.235986+00	17	Image for Female nice bum short	1	[{"added": {}}]	17	1
36	2026-04-26 07:16:07.85436+00	8	Female black slim jean	1	[{"added": {}}]	13	1
37	2026-04-26 07:16:33.291123+00	8	Female black slim jean	1	[{"added": {}}]	16	1
38	2026-04-26 07:18:04.805257+00	18	Image for Female black slim jean	1	[{"added": {}}]	17	1
39	2026-04-26 07:18:21.5012+00	19	Image for Female black slim jean	1	[{"added": {}}]	17	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	authtoken	token
8	authtoken	tokenproxy
9	django_rest_passwordreset	resetpasswordtoken
10	payments	payment
11	users	address
12	shop	cart
13	shop	category
14	shop	enquiry
15	shop	order
16	shop	product
17	shop	productimage
18	shop	review
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-12 21:37:42.021843+00
2	auth	0001_initial	2026-04-12 21:37:49.379235+00
3	admin	0001_initial	2026-04-12 21:37:51.331677+00
4	admin	0002_logentry_remove_auto_add	2026-04-12 21:37:51.592733+00
5	admin	0003_logentry_add_action_flag_choices	2026-04-12 21:37:52.344727+00
6	contenttypes	0002_remove_content_type_name	2026-04-12 21:37:53.854529+00
7	auth	0002_alter_permission_name_max_length	2026-04-12 21:37:54.927544+00
8	auth	0003_alter_user_email_max_length	2026-04-12 21:37:55.900653+00
9	auth	0004_alter_user_username_opts	2026-04-12 21:37:56.381814+00
10	auth	0005_alter_user_last_login_null	2026-04-12 21:37:57.616026+00
11	auth	0006_require_contenttypes_0002	2026-04-12 21:37:58.113273+00
12	auth	0007_alter_validators_add_error_messages	2026-04-12 21:37:58.877094+00
13	auth	0008_alter_user_username_max_length	2026-04-12 21:38:00.110484+00
14	auth	0009_alter_user_last_name_max_length	2026-04-12 21:38:01.150231+00
15	auth	0010_alter_group_name_max_length	2026-04-12 21:38:02.124299+00
16	auth	0011_update_proxy_permissions	2026-04-12 21:38:02.614521+00
17	auth	0012_alter_user_first_name_max_length	2026-04-12 21:38:03.877842+00
18	authtoken	0001_initial	2026-04-12 21:38:05.630882+00
19	authtoken	0002_auto_20160226_1747	2026-04-12 21:38:06.03275+00
20	authtoken	0003_tokenproxy	2026-04-12 21:38:06.848402+00
21	authtoken	0004_alter_tokenproxy_options	2026-04-12 21:38:07.62754+00
22	django_rest_passwordreset	0001_initial	2026-04-12 21:38:10.70255+00
23	django_rest_passwordreset	0002_pk_migration	2026-04-12 21:38:13.128816+00
24	django_rest_passwordreset	0003_allow_blank_and_null_fields	2026-04-12 21:38:14.169805+00
25	django_rest_passwordreset	0004_alter_resetpasswordtoken_user_agent	2026-04-12 21:38:15.190926+00
26	payments	0001_initial	2026-04-12 21:38:17.134246+00
27	payments	0002_payment_updated_at	2026-04-12 21:38:18.161037+00
28	sessions	0001_initial	2026-04-12 21:38:19.913076+00
29	shop	0001_initial	2026-04-12 21:38:25.760244+00
30	shop	0002_order	2026-04-12 21:38:27.264453+00
31	shop	0003_alter_productimage_image	2026-04-25 22:04:39.74311+00
32	shop	0004_remove_productimage_image_productimage_image_url	2026-04-25 22:04:39.759977+00
\.


--
-- Data for Name: django_rest_passwordreset_resetpasswordtoken; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.django_rest_passwordreset_resetpasswordtoken (created_at, key, ip_address, user_agent, user_id, id) FROM stdin;
2026-04-21 21:02:50.516765+00	cb28b4a3a1580e	127.0.0.1	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36	5	5
2026-04-21 21:04:33.574238+00	36ddd05458f69f37314ed870ab78cf7188	127.0.0.1	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36	8	6
2026-04-21 21:04:53.135386+00	a28b5f00e99b2454f8df46b	127.0.0.1	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36	4	7
2026-04-22 06:04:21.551088+00	9ed0f78627460801c774bc0ae68c7d2f44	127.0.0.1	Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Mobile Safari/537.36	3	8
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
xhrtuoi3ua1cc5s4y2r479hw5fdso5qi	.eJxVjEEOwiAQRe_C2hBmKAgu3fcMhGGoVA0kpV0Z765NutDtf-_9lwhxW0vYel7CzOIiQJx-N4rpkesO-B7rrcnU6rrMJHdFHrTLsXF-Xg_376DEXr61A2SrkJMn53RWCZGGc9SEhtB6CxCnAbVi6w0kZFY8JcoGQHtnNYn3B8uPN1o:1wEEIq:zIZJ3yIuibe3uc2sztlaW_uQXGv-W3pwHvQmlmEqYpc	2026-05-02 22:38:16.959137+00
uavgdawgfz8cd2hcnivmvdp74ukh54on	.eJxVjEEOwiAQRe_C2hBmKAgu3fcMhGGoVA0kpV0Z765NutDtf-_9lwhxW0vYel7CzOIiQJx-N4rpkesO-B7rrcnU6rrMJHdFHrTLsXF-Xg_376DEXr61A2SrkJMn53RWCZGGc9SEhtB6CxCnAbVi6w0kZFY8JcoGQHtnNYn3B8uPN1o:1wIBtE:pAKSFOBcHLaNARRWgk68pbwX7NnmXWQrSG1m0s1_Kss	2026-05-13 20:52:12.143194+00
\.


--
-- Data for Name: payments_payment; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.payments_payment (id, amount, reference, status, created_at, user_id, updated_at) FROM stdin;
1	1200.00	5B6E85B78ADC4F2FAC7D391D656DCE8C	pending	2026-04-16 06:33:38.691288+00	4	2026-04-16 06:33:38.691302+00
2	3600.00	6F65DD6B72F743158A0AFEBF971F4D04	pending	2026-04-16 07:56:11.441481+00	5	2026-04-16 07:56:11.441495+00
3	3600.00	3860690326BF474981246136FDCEE0D5	pending	2026-04-16 07:57:05.96171+00	5	2026-04-16 07:57:05.961722+00
4	1200.00	72ECF4C7A9584BC4BE2546423A33E78C	pending	2026-04-16 08:08:25.881213+00	6	2026-04-16 08:08:25.881224+00
5	6000.00	5E4706BD4CFE46E2BBC38E4ED7033913	pending	2026-04-19 11:58:37.31207+00	3	2026-04-19 11:58:37.312086+00
6	1200.00	4F346698209841C198B3BDB0C6FE571B	pending	2026-04-19 13:21:03.930333+00	3	2026-04-19 13:21:03.93035+00
7	1200.00	9CE844BF0D5B44C9A298F1A34A83E090	pending	2026-04-19 14:24:40.926751+00	3	2026-04-19 14:24:40.926762+00
8	1200.00	526EF708BBF8499FAC7CBB342239CFE2	pending	2026-04-19 20:44:08.111706+00	8	2026-04-19 20:44:08.111719+00
9	1200.00	55B89C2047574A518CB9088B2F52D408	pending	2026-04-19 21:21:56.372125+00	3	2026-04-19 21:21:56.372138+00
10	1200.00	BE81C7EEE8734BCF9A4CC94FD8079BC2	pending	2026-04-20 20:13:08.009708+00	5	2026-04-20 20:13:08.00972+00
11	1200.00	D1EF56DB42444CCB9DEFF732B050A3E1	pending	2026-04-20 20:25:17.784979+00	5	2026-04-20 20:25:17.785052+00
12	1200.00	1D21AD48303D4C0CBDDE39DD66BC861A	pending	2026-04-20 21:24:41.050242+00	12	2026-04-20 21:24:41.050256+00
13	1200.00	D474706939154FDBB6E6D1ED895C0666	pending	2026-04-20 21:25:18.470726+00	12	2026-04-20 21:25:18.470741+00
14	4200.00	23677CEE0494486D994A6C7239C6123D	pending	2026-04-21 20:55:06.264227+00	5	2026-04-21 20:55:06.26424+00
15	1000.00	E88E8E26AED44250A1323B6D87DCF89A	pending	2026-04-21 21:14:11.99748+00	13	2026-04-21 21:14:11.997493+00
\.


--
-- Data for Name: shop_cart; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.shop_cart (id, quantity, created_at, user_id, product_id) FROM stdin;
\.


--
-- Data for Name: shop_category; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.shop_category (id, name, slug) FROM stdin;
1	Summer design	summer-design
2	A new summer wear	a-new-summer-wear
3	Spring female jacket	spring-female-jacket
4	male jean, top and show	male-jean-top-and-show
5	Male summer jacket	male-summer-jacket
6	Female bum short	female-bum-short
7	Female nice bum short	female-nice-bum-short
8	Female black slim jean	female-black-slim-jean
\.


--
-- Data for Name: shop_enquiry; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.shop_enquiry (id, name, email, message, created_at) FROM stdin;
\.


--
-- Data for Name: shop_order; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.shop_order (id, full_name, email, phone, billing_address, shipping_address, total_amount, status, created_at, user_id) FROM stdin;
1	Gid	gidfrank00@gmail.com	09060485846	ikola road, wazobia market, lagos, Nigeria	ikola road, wazobia market, lagos, Nigeria	1200.00	pending	2026-04-16 06:33:31.986441+00	4
2	Glory Uzo	uzoglory840@gmail.com	09060485846	ikola road, wazobia market, lagos, Nigeria	ikola road, wazobia market, lagos, Nigeria	3600.00	pending	2026-04-16 07:56:09.441241+00	5
3	Glory Uzo	uzoglory840@gmail.com	09060485846	ikola road, wazobia market, lagos, Nigeria	ikola road, wazobia market, lagos, Nigeria	3600.00	pending	2026-04-16 07:57:04.186509+00	5
4	Gideon Eki	gekibade@gmail.com	09011833211	20 Shagamu road, wazobia market, lagos, Nigeria	20 Shagamu road, wazobia market, lagos, Nigeria	1200.00	pending	2026-04-16 08:08:23.884801+00	6
5	Mark gee	g.mark700@yahoo.com	09060485846	Nigeria	Nigeria	6000.00	pending	2026-04-19 11:58:33.685309+00	3
6	mark gee	g.mark700@yahoo.com	09060485846	Nigeria	Nigeria	1200.00	pending	2026-04-19 13:21:01.910428+00	3
7	g mark	g.mark700@yahoo.com	09060485846	Nigeria	Nigeria	1200.00	pending	2026-04-19 14:24:38.481647+00	3
8	Frank Gee	gefrank59@gmail.com	09060485846	Nigeria	Nigeria	1200.00	pending	2026-04-19 20:43:56.603594+00	8
9	Glory Uzo	uzoglory840@gmail.com	09060485846	ikola road, wazobia market, lagos, Nigeria	ikola road, wazobia market, lagos, Nigeria	1200.00	pending	2026-04-19 21:21:54.52802+00	3
10	Glory Uzo	uzoglory840@gmail.com	09060485846	ikola road, wazobia market, lagos, Nigeria	ikola road, wazobia market, lagos, Nigeria	1200.00	pending	2026-04-20 20:13:05.790122+00	5
11	Glory Uzo	uzoglory840@gmail.com	09060485846	ikola road, wazobia market, lagos, Nigeria	ikola road, wazobia market, lagos, Nigeria	1200.00	pending	2026-04-20 20:25:16.02035+00	5
12	Glory Uzo	uzoglory840@gmail.com	09060485846	ikola road, wazobia market, lagos, Nigeria	ikola road, wazobia market, lagos, Nigeria	1200.00	pending	2026-04-20 21:24:38.788233+00	12
13	Glory Uzo	uzoglory840@gmail.com	09060485846	ikola road, wazobia market, lagos, Nigeria	ikola road, wazobia market, lagos, Nigeria	4200.00	pending	2026-04-21 20:54:59.268652+00	5
14	Glory	glory.ekibade@toriloacademy.com	09060485846	Nigeria	Nigeria	1000.00	pending	2026-04-21 21:14:10.079318+00	13
\.


--
-- Data for Name: shop_product; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.shop_product (id, "SIZES", "COLOR", name, slug, price, description, stock, is_active, created_at, category_id) FROM stdin;
1	M	BLACK	Summer design	summer-design	1200.00	Summer design	1	t	2026-04-13 17:13:52.662739+00	1
2	M	WHITE	A new summer wear	a-new-summer-wear	1000.00	A new summer wear that serves its purpose	2	t	2026-04-20 21:33:55.307913+00	2
3	M	BLUE	Spring female jacket	spring-female-jacket	800.00	Spring female jacket	2	t	2026-04-26 06:36:42.058637+00	3
4	M	BLUE	Male jean, top and show	male-jean-top-and-show	1300.00	Male jean, top and show	2	t	2026-04-26 07:02:48.668234+00	4
5	M	BLUE	Male summer jacket	male-summer-jacket	1100.00	Male summer jacket	1	t	2026-04-26 07:05:28.515584+00	5
6	M	BLUE	Female bum short	female-bum-short	800.00	Female bum short	3	t	2026-04-26 07:09:40.211312+00	6
7	M	BLACK	Female nice bum short	female-nice-bum-short	900.00	Female nice bum short	5	t	2026-04-26 07:11:55.330377+00	7
8	M	BLACK	Female black slim jean	female-black-slim-jean	900.00	Female black slim jean	3	t	2026-04-26 07:16:33.289708+00	8
\.


--
-- Data for Name: shop_productimage; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.shop_productimage (id, product_id, image_url) FROM stdin;
1	1	\N
2	1	\N
3	2	\N
4	2	\N
7	1	https://images.unsplash.com/photo-1739300293786-7fba041e7cf1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
8	1	https://images.unsplash.com/photo-1739301673974-b0204a01e8bf?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
9	3	https://images.unsplash.com/photo-1708857150611-c5af2d168338?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
10	3	https://images.unsplash.com/photo-1708857150721-72b07b719e64?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
11	3	https://images.unsplash.com/photo-1708857150611-c5af2d168338?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
12	2	https://images.unsplash.com/photo-1772450235995-ecd6b9c17aab?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
13	4	https://images.unsplash.com/photo-1649879681586-4f63a6ed7d19?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
14	4	https://images.unsplash.com/photo-1649879681621-1dca028bed57?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
15	5	https://plus.unsplash.com/premium_photo-1727942421760-624e3e958b5e?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
16	6	https://plus.unsplash.com/premium_photo-1689575249488-aca091ed2eec?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
17	7	https://images.unsplash.com/photo-1562276298-72d9f22b1dc6?q=80&w=731&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
18	8	https://images.unsplash.com/photo-1637562772855-c9a1012c689c?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
19	8	https://images.unsplash.com/photo-1587028971442-aa483a05136a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
\.


--
-- Data for Name: shop_review; Type: TABLE DATA; Schema: public; Owner: masco_db_user
--

COPY public.shop_review (id, rating, comment, created_at, product_id, user_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 13, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 39, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 32, true);


--
-- Name: django_rest_passwordreset_resetpasswordtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.django_rest_passwordreset_resetpasswordtoken_id_seq', 8, true);


--
-- Name: payments_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.payments_payment_id_seq', 15, true);


--
-- Name: shop_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.shop_cart_id_seq', 1, false);


--
-- Name: shop_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.shop_category_id_seq', 8, true);


--
-- Name: shop_enquiry_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.shop_enquiry_id_seq', 1, false);


--
-- Name: shop_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.shop_order_id_seq', 14, true);


--
-- Name: shop_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.shop_product_id_seq', 8, true);


--
-- Name: shop_productimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.shop_productimage_id_seq', 19, true);


--
-- Name: shop_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: masco_db_user
--

SELECT pg_catalog.setval('public.shop_review_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_rest_passwordreset_resetpasswordtoken django_rest_passwordreset_resetpasswordtoken_key_f1b65873_uniq; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.django_rest_passwordreset_resetpasswordtoken
    ADD CONSTRAINT django_rest_passwordreset_resetpasswordtoken_key_f1b65873_uniq UNIQUE (key);


--
-- Name: django_rest_passwordreset_resetpasswordtoken django_rest_passwordreset_resetpasswordtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.django_rest_passwordreset_resetpasswordtoken
    ADD CONSTRAINT django_rest_passwordreset_resetpasswordtoken_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: payments_payment payments_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_pkey PRIMARY KEY (id);


--
-- Name: payments_payment payments_payment_reference_key; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_reference_key UNIQUE (reference);


--
-- Name: shop_cart shop_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_cart
    ADD CONSTRAINT shop_cart_pkey PRIMARY KEY (id);


--
-- Name: shop_category shop_category_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_category
    ADD CONSTRAINT shop_category_pkey PRIMARY KEY (id);


--
-- Name: shop_category shop_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_category
    ADD CONSTRAINT shop_category_slug_key UNIQUE (slug);


--
-- Name: shop_enquiry shop_enquiry_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_enquiry
    ADD CONSTRAINT shop_enquiry_pkey PRIMARY KEY (id);


--
-- Name: shop_order shop_order_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_order
    ADD CONSTRAINT shop_order_pkey PRIMARY KEY (id);


--
-- Name: shop_product shop_product_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_product
    ADD CONSTRAINT shop_product_pkey PRIMARY KEY (id);


--
-- Name: shop_product shop_product_slug_key; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_product
    ADD CONSTRAINT shop_product_slug_key UNIQUE (slug);


--
-- Name: shop_productimage shop_productimage_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_productimage
    ADD CONSTRAINT shop_productimage_pkey PRIMARY KEY (id);


--
-- Name: shop_review shop_review_pkey; Type: CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_review
    ADD CONSTRAINT shop_review_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_rest_passwordreset_resetpasswordtoken_key_f1b65873_like; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX django_rest_passwordreset_resetpasswordtoken_key_f1b65873_like ON public.django_rest_passwordreset_resetpasswordtoken USING btree (key varchar_pattern_ops);


--
-- Name: django_rest_passwordreset_resetpasswordtoken_user_id_e8015b11; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX django_rest_passwordreset_resetpasswordtoken_user_id_e8015b11 ON public.django_rest_passwordreset_resetpasswordtoken USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: payments_payment_reference_1d502039_like; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX payments_payment_reference_1d502039_like ON public.payments_payment USING btree (reference varchar_pattern_ops);


--
-- Name: payments_payment_user_id_f9db060a; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX payments_payment_user_id_f9db060a ON public.payments_payment USING btree (user_id);


--
-- Name: shop_cart_product_id_48b482ee; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX shop_cart_product_id_48b482ee ON public.shop_cart USING btree (product_id);


--
-- Name: shop_cart_user_id_27925ac6; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX shop_cart_user_id_27925ac6 ON public.shop_cart USING btree (user_id);


--
-- Name: shop_category_slug_4508178e_like; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX shop_category_slug_4508178e_like ON public.shop_category USING btree (slug varchar_pattern_ops);


--
-- Name: shop_order_user_id_00aba627; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX shop_order_user_id_00aba627 ON public.shop_order USING btree (user_id);


--
-- Name: shop_product_category_id_14d7eea8; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX shop_product_category_id_14d7eea8 ON public.shop_product USING btree (category_id);


--
-- Name: shop_product_slug_30bd2d5d_like; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX shop_product_slug_30bd2d5d_like ON public.shop_product USING btree (slug varchar_pattern_ops);


--
-- Name: shop_productimage_product_id_65b3b20c; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX shop_productimage_product_id_65b3b20c ON public.shop_productimage USING btree (product_id);


--
-- Name: shop_review_product_id_f74dddfd; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX shop_review_product_id_f74dddfd ON public.shop_review USING btree (product_id);


--
-- Name: shop_review_user_id_02dce754; Type: INDEX; Schema: public; Owner: masco_db_user
--

CREATE INDEX shop_review_user_id_02dce754 ON public.shop_review USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_rest_passwordreset_resetpasswordtoken django_rest_password_user_id_e8015b11_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.django_rest_passwordreset_resetpasswordtoken
    ADD CONSTRAINT django_rest_password_user_id_e8015b11_fk_auth_user FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_payment payments_payment_user_id_f9db060a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_user_id_f9db060a_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_cart shop_cart_product_id_48b482ee_fk_shop_product_id; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_cart
    ADD CONSTRAINT shop_cart_product_id_48b482ee_fk_shop_product_id FOREIGN KEY (product_id) REFERENCES public.shop_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_cart shop_cart_user_id_27925ac6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_cart
    ADD CONSTRAINT shop_cart_user_id_27925ac6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_order shop_order_user_id_00aba627_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_order
    ADD CONSTRAINT shop_order_user_id_00aba627_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_product shop_product_category_id_14d7eea8_fk_shop_category_id; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_product
    ADD CONSTRAINT shop_product_category_id_14d7eea8_fk_shop_category_id FOREIGN KEY (category_id) REFERENCES public.shop_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_productimage shop_productimage_product_id_65b3b20c_fk_shop_product_id; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_productimage
    ADD CONSTRAINT shop_productimage_product_id_65b3b20c_fk_shop_product_id FOREIGN KEY (product_id) REFERENCES public.shop_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_review shop_review_product_id_f74dddfd_fk_shop_product_id; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_review
    ADD CONSTRAINT shop_review_product_id_f74dddfd_fk_shop_product_id FOREIGN KEY (product_id) REFERENCES public.shop_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: shop_review shop_review_user_id_02dce754_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: masco_db_user
--

ALTER TABLE ONLY public.shop_review
    ADD CONSTRAINT shop_review_user_id_02dce754_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO masco_db_user;


--
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO masco_db_user;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO masco_db_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO masco_db_user;


--
-- PostgreSQL database dump complete
--

\unrestrict dZUVOeF3aXlo9yT5n30vqAU6dNkoAtLx1kkd9pXqsbfajmAkSG0bc6S3sfpznGg

