# Generated by Django 6.0.2 on 2026-08-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_productimage_image_productimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='selected_size',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
